library(jsonlite)
library(dplyr)
library(stringr)
library(ggplot2)
library(plotly)


all_teams <- c("AlleyCats",
               "Aviators",
               "Breeze",
               "Cannons",
               "Cascades",
               "Dragons",
               "Empire",
               "Express",
               "FlameThrowers",
               "Flyers",
               "Glory",
               "Growlers",
               "Hustle",
               "Legion",
               "Lions",
               "Mechanix",
               "Nightwatch",
               "Nitro",
               "Outlaws",
               "Phoenix",
               "Radicals",
               "Revolution",
               "Riptide",
               "Royal",
               "Rush", 
               "Shred",
               "Sol",
               "Spiders",
               "Summit",
               "Thunderbirds",
               "Union",
               "Wind Chill") 

all_codes <- c("IND",
               "LA",
               "DC",
               "TB",
               "SEA",
               "ROC",
               "NY",
               "CHA",
               "SF",
               "CAR",
               "BOS",
               "SD",
               "ATL",
               "DAL",
               "SAL",
               "DET",
               "NSH",
               "POR",
               "OTT",
               "PHI",
               "MAD",
               "CIN",
               "VAN",
               "MTL",
               "TOR",
               "SLC",
               "ATX",
               "OAK",
               "COL",
               "PIT",
               "CHI",
               "MIN")

current_teams <- c("AlleyCats",
                   "Aviators",
                   "Breeze",
                   "Cannons",
                   "Cascades",
                   "Empire",
                   "Flyers",
                   "Glory",
                   "Growlers",
                   "Hustle",
                   "Legion",
                   "Mechanix",
                   "Nitro",
                   "Outlaws",
                   "Phoenix",
                   "Radicals",
                   "Royal",
                   "Rush",
                   "Shred",
                   "Sol",
                   "Spiders",
                   "Summit",
                   "Thunderbirds",
                   "Union",
                   "Wind Chill")

all_Ids <- c("alleycats",     "aviators" ,     "breeze"    ,    "cannons"    ,   "cascades"    ,  "dragons"    ,   "empire"   ,     "express" ,     
             "flamethrowers" ,"flyers"    ,    "glory"  ,       "growlers"   ,   "hustle"  ,      "legion"      ,  "lions"   ,      "mechanix"  ,   
             "nightwatch" ,   "nitro" ,        "outlaws"  ,     "phoenix"  ,     "radicals"  ,    "revolution" ,   "riptide"      , "royal"   ,     
             "rush"      ,    "shred"   ,      "sol"    ,       "spiders"    ,   "summit"   ,     "thunderbirds" , "union"     ,    "windchill")


regions <- c("Central", "West", "East", "South", "West", NA, "East", NA, NA, "South", "East", "West", "South", "South", NA, "Central",
             NA, "West", "East", "East", "Central", NA, NA, "East", "East", "West", "South", "West", "West", "Central", "Central", "Central")

team_df <- data.frame(teamName = all_teams,
                      teamCode = all_codes,
                      teamID = all_Ids,
                      region = regions)   
